# Generated by Django 2.2.19 on 2022-02-12 10:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Employer name', max_length=256, verbose_name='Employer name')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number should be like 7XXXXXXXXXX (X - numbers from 0 to 9)', regex='^(7)?[0-9]{10}$')])),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Store', max_length=256, verbose_name='Store')),
                ('employer', models.ForeignKey(help_text='Employer', on_delete=django.db.models.deletion.CASCADE, related_name='store', to='api.Employer', verbose_name='Employer')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Visit date', verbose_name='Date')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('store', models.ForeignKey(help_text='Store', on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='api.Store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
            },
        ),
    ]
